language: android

# branches:
#     only:
#         - master

matrix:
    include:
        - os: osx
          env: PLATFORM=osx
          osx_image: xcode8.3
          compiler: clang
        - os: linux
          env: PLATFORM=linux CXX=g++-4.8 CC=gcc-4.8
          addons:
            apt:
              sources: [ 'kubuntu-backports', 'ubuntu-toolchain-r-test', 'george-edison55-precise-backports' ]
              packages: [ 'cmake', 'gcc-multilib', 'g++-multilib' ]
        - os: linux
          env: PLATFORM=android
          addons:
            apt:
              sources: [ 'kubuntu-backports', 'george-edison55-precise-backports' ]
              packages: [ 'cmake', 'lib32z1-dev', 'lib32stdc++6' ]
          android:
            components: [ 'tools', 'build-tools-25.0.2', 'extra-android-m2repository', 'android-25' ]
          jdk: oraclejdk8

before_install:
    - chmod a+x ./.travis/install.sh
    - chmod a+x ./.travis/build.sh
install:
    - source ./.travis/install.sh
script:
    - source ./.travis/build.sh
